export const ADD_BUY_ORDER = "ADD_BUY_ORDER";
export const ADD_SELL_ORDER = "ADD_SELL_ORDER";

export const FETCH_BUY_ORDERS = "FETCH_BUY_ORDERS";
export const LOAD_BUY_ORDERS = "LOAD_BUY_ORDERS";
export const RECEIVE_BUY_ORDERS = "RECEIVE_BUY_ORDERS";

export const FETCH_SELL_ORDERS = "FETCH_SELL_ORDERS";
export const LOAD_SELL_ORDERS = "LOAD_SELL_ORDERS";
export const RECEIVE_SELL_ORDERS = "RECEIVE_SELL_ORDERS";

export const CONFIRM_ORDER = "CONFIRM_ORDER";

export const FETCH_TRADES = "FETCH_TRADES";
export const RECEIVE_TRADES = "RECEIVE_TRADES";

export const SELECT_ORDER_TYPE = "SELECT_ORDER_TYPE";
export const SET_ORDER_FORM_VALUES = "SET_ORDER_FORM_VALUES";
export const SET_ACCEPT_FORM_VALUES = "SET_ACCEPT_FORM_VALUES";

export const FETCH_ETH_CONTEXT = "FETCH_ETH_CONTEXT";
export const RECEIVE_ETH_CONTEXT = "RECEIVE_ETH_CONTEXT";

export const RECEIVE_AUTH = "RECEIVE_AUTH";

export const RECEIVE_ZONE_BALANCES = "RECEIVE_ZONE_BALANCE"S;

export const FETCH_BALANCE_WATER = "FETCH_BALANCE_WATER";
export const RECEIVE_BALANCE_WATER = "RECEIVE_BALANCE_WATER";

export const FETCH_LICENCE = "FETCH_LICENCE";
export const RECEIVE_LICENCE = "RECEIVE_LICENCE";
export const SET_ACTIVE_LICENCE = "SET_ACTIVE_LICENCE";

export const FETCH_WATER_ACCOUNTS = "FETCH_WATER_ACCOUNTS";
export const RECEIVE_WATER_ACCOUNTS = "RECEIVE_WATER_ACCOUNTS";
export const SET_ACTIVE_WATER_ACCOUNT = "SET_ACTIVE_WATER_ACCOUNT";

export const RECEIVE_LICENCES = "RECEIVE_LICENCES";
export const RECEIVE_ADMIN_LICENCES = "RECEIVE_ADMIN_LICENCES";

export const MODAL_ORDER_FORM_SET = "MODAL_ORDER_FORM_SET";
export const MODAL_ACCEPT_ORDER_SET = "MODAL_ACCEPT_ORDER_SET";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const WATCH_EVENT_MATCH = "WATCH_EVENT_MATCH";

export const ORDER_TYPE_SELL = "sell";
export const ORDER_TYPE_BUY = "buy";
